dna = "CTTTCCAGATCGAACCGCCTACTCAAGATGCCGGTCCTTGCTTCATCGAACAACGGCATGTCGTTCCAGAGTACCGGATGACATTGTTTGACGGGGTCACATGATACGTATCGTTGTGCGGCTACAGGCTGATCCGGGGGGTTCTGTCGCCCTTAAAGGATGGCTCGGGATGAGGACATAACGGACTATACGTGTCGTGAACTGCTAAAAAATCACAAATCGGTGCGTCGCGCATGGAGACCCATGTTTGCCTGCTGCCCATCGATCTATATGGGGCGTATGTACCATGCCCCGCGCGCAGGATCGTGTAATAACCCGGCAGTCACGCAGGAAGTAAGGCATAGCAACTCAGTGGGTGCGTCCCCGCGTGTAACAGGTCATGCCTAACATGATGTTCTGAGTCCACCTAACCTTGAGCACTATGGAACAGATTGTGAAATGTCTCCTGTGGATTAGAAGGACCCAGTGACCCACTGCCATCCTACGTTTTGGCCTCAGCGAGGAAGAATAAGGGACTCGCCATGCCGGAAGTAACACATAAAGGCAATGAGCTTACCGGACACCTTGGTGGGTGCTTCTCCGGGTCCGACAGACAATTCCGTCCACACGCTCGGTGCGGTTAGGTTGCCTCTCAGGTCTGGGCTCAGTCGGTAATATTGCTGCAGCACCACAAACATTGAAGTACCGAGAATGCCTTTGCTTAGAACAACTATGTGGGTCGATATTGCTGCGACATGTACTGTGAAGACAACGTCTCTGCTGCTGGGGGACCGGCCACCGCGGGAACGGGATCATATTTGTTAACCCTGTAATGACATTAGTCGAAACCAGACCTGACTGCAATGGGGTGATTTGCACCGTCCCCTTTTGACGCCAGTTCCAGCAGGGCTGAACCAAGTCTGCTCTTGTGGGGAAATTCTCACAGGAGTCGGCCTCAAGTTGCAATCCACTCAGCATTTCCTCAC"
adenine = 0
for a in dna:
	if a == "A":
		adenine = adenine + 1
		
guanine = 0
for g in dna:
	if g == "G":
		guanine = guanine + 1

cytosine = 0
for c in dna:
	if c == "C":
		cytosine = cytosine + 1
		
thym = 0
for t in dna:
	if t == "T":
		thym = thym + 1
		
print adenine, cytosine, guanine, thym